# Generated by Django 3.0.7 on 2020-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='price',
            field=models.IntegerField(),
        ),
    ]
